kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logsdata
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instarent-login-deployment
  labels:
    app: instarent-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instarent-login
  template:
    metadata:
      labels:
        app: instarent-login
    spec:
      containers:
      - name: loginservice
        image: instarent.azurecr.io/instarentlogin:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: ASPNETCORE_URLS
          value: "https://+;http://+"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "8b6039b6-c67a-448b-977b-0ce6d3fcfd49"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/dev-cert/localhost.pfx"
        - name: App__SelfUrl
          value: "https://login.instarentshop.com"
        - name: App__CorsOrigins
          value: "https://webgateway-service,http://webgateway-service,https://webgateway.instarentshop.com,http://webgateway.instarentshop.com"
        - name: ConnectionStrings__InstaRent 
          value: "Server=tcp:instarent.database.windows.net,1433;Initial Catalog=InstaRent;Persist Security Info=False;User ID=instarentadmin;Password=Pa$$w0rd**;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
          
        volumeMounts:
        - mountPath: /dev-cert
          name: dev-cert
        - mountPath: /app/Logs
          name: loginlogsdata 
          subPathExpr: login/$(POD_NAME) 
          
      imagePullSecrets:
      - name: regcred          
      volumes:
      - name: dev-cert
        secret:
          secretName: instranet-cert     
      - name: loginlogsdata
        persistentVolumeClaim:
          claimName: logsdata        
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: ClusterIP
  selector:
    app: instarent-login
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
      #nodePort: 32020 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      #nodePort: 30020 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)      
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-login-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: instarent-login-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 70