apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: ClusterIP
  selector:
    app: instarent-login
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
      #nodePort: 32020 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      #nodePort: 30020 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)      
