on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: instarent.azurecr.io
        username: ${{ secrets.acr_instarent_username }}
        password: ${{ secrets.acr_instarent_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/host/InstaRent.Login.HttpApi.Host" -f  "host/InstaRent.Login.HttpApi.Host/Dockerfile" -t instarent.azurecr.io/instarentaks:${{ github.sha }} --label dockerfile-path=host/InstaRent.Login.HttpApi.Host/Dockerfile
        docker push instarent.azurecr.io/instarentaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_instarentaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: instarent.azurecr.io
        container-registry-username: ${{ secrets.acr_instarent_username }}
        container-registry-password: ${{ secrets.acr_instarent_password }}
        secret-name: instarentaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          instarent.azurecr.io/instarentaks:${{ github.sha }}
        imagepullsecrets: |
          instarentaksdockerauth
